

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fwfurtado/eats
          search-paths: config-files

  profiles:
    active: git
server:
  port: 8888

eureka:
  client:
    enabled: false
