server:
  port: 0


geocoder:
  url: https://locationiq.com/v1/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password:

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://ec2-123-amazon.com/restaurant
    username: root
    password:

