zuul:
  routes:
    sensitive-headers:
    breweries:
      strip-prefix: false
      url: https://api.openbrewerydb.org
    home:
      url: forward:/home

search:
  url: http://search/

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.cloud.netflix.zuul: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
