zuul:
  routes:
    sensitive-headers:
    distancia:
      url: http://localhost:8020
    breweries:
      strip-prefix: false
      url: https://api.openbrewerydb.org
    home:
      url: forward:/home
    monolito:
      path: /**
      url: http://localhost:8010

ribbon:
  eureka:
    enabled: false

logging:
  level:
    org.springframework.cloud.netflix.zuul: DEBUG