version: '3.7'

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: eats
      MYSQL_PASSWORD: 123456
    volumes:
      - mysql:/var/lib/mysql

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
      - mongo:/data/db

  rabbit:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: 123456
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - rabbit:/var/lib/rabbitmq
      - ./rabbit/enable_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  mysql:
  mongo:
  rabbit:

