server:
  port: 8111



management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  cloud:
    stream:
      bindings:
        search-in:
          destination: search
          group: search-app
        search-out:
          destination: search